env:
  OPENBLAS_NUM_THREADS: 1

steps:
  - label: "Build docs"
    command:
      - "singularity pull $$SINGULARITY_CONTAINER"
      - "SINGULARITY_BIND=\"/data:$$JULIA_DEPOT_PATH\""
      - "echo $$SINGULARITY_BIND"
      - "singularity run $$SINGULARITY_CONTAINER julia -e 'using Pkg; Pkg.instantiate()'"
      - "singularity run $$SINGULARITY_CONTAINER julia -e 'using Pkg; Pkg.precompile()'"
      - "singularity run $$SINGULARITY_CONTAINER julia --procs=auto docs/make.jl"
    env:
      JULIA_PROJECT: "docs/"
      CLIMATEMACHINE_SETTINGS_DISABLE_GPU: "true"
      CLIMATEMACHINE_SETTINGS_FIX_RNG_SEED: "true"
      CLIMATEMACHINE_SETTINGS_DISABLE_CUSTOM_LOGGER: "true"
      SINGULARITY_CONTAINER: "library://jakebolewski/clima/documenter.sif:1.0.0" 
    agents:
      config: cpu
      queue: central
      slurm_nodes: 1
