env:
  OPENBLAS_NUM_THREADS: 1
  CLIMATEMACHINE_SETTINGS_FIX_RNG_SEED: "true"

steps:
  - label: "gpu_AtmosLES_dycoms"
    key: "gpu_AtmosLES_dycoms"
    command:
      - "mpiexec julia --color=yes --project experiments/AtmosLES/dycoms.jl"
    agents:
      config: gpu
      queue: central
      slurm_ntasks: 3
      slurm_gres: "gpu:1"

