[[ParametersType]]
path = "../ParametersType"
uuid = "046d00ba-03b1-11e9-3cca-b5213a01defd"
version = "0.0.0"

[[PlanetParameters]]
deps = ["ParametersType"]
path = "../PlanetParameters"
uuid = "50a4fe1a-031f-11e9-2493-0505e0da639e"
version = "0.0.0"

[[Roots]]
deps = ["Compat", "Printf"]
git-tree-sha1 = "2e7171b6f3b58b81201ba37d9e1220aff6d904a1"
uuid = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
version = "0.7.4"
